language: objective-c
osx_image: xcode9
podfile: Example/Podfile
env:
   global:
   - LANG=en_US.UTF-8

before_install:
 - rvm install ruby-2.4.2
 - gem install bundler
 - bundle install
 - bundle exec pod repo update
 - bundle exec pod install --project-directory=Example

script:
 - bundle exec danger
 - bundle exec pod lib lint --quick
 - bundle exec rake test

after_success:
 - bash <(curl -s https://codecov.io/bash)
